export const cardBackArt = new URL('../assets/cards/card-back.png', import.meta.url).href
export const runtimeTableArt = new URL('../assets/scenes/scene-runtime-market-table-8p.png', import.meta.url).href

export const cardArt: Record<string, string> = {
  'fruit-01': new URL('../assets/cards/fruit-01-apple.png', import.meta.url).href,
  'fruit-02': new URL('../assets/cards/fruit-02-pear.png', import.meta.url).href,
  'fruit-03': new URL('../assets/cards/fruit-03-orange.png', import.meta.url).href,
  'fruit-04': new URL('../assets/cards/fruit-04-peach.png', import.meta.url).href,
  'fruit-05': new URL('../assets/cards/fruit-05-plum.png', import.meta.url).href,
  'fruit-06': new URL('../assets/cards/fruit-06-apricot.png', import.meta.url).href,
  'fruit-07': new URL('../assets/cards/fruit-07-guava.png', import.meta.url).href,
  'fruit-08': new URL('../assets/cards/fruit-08-dragon-fruit.png', import.meta.url).href,
  'fruit-09': new URL('../assets/cards/fruit-09-banana.png', import.meta.url).href,
  'fruit-10': new URL('../assets/cards/fruit-10-starfruit.png', import.meta.url).href,
  'fruit-11': new URL('../assets/cards/fruit-11-passion-fruit.png', import.meta.url).href,
  'fruit-12': new URL('../assets/cards/fruit-12-lemon.png', import.meta.url).href,
  'fruit-13': new URL('../assets/cards/fruit-13-lime.png', import.meta.url).href,
  'fruit-14': new URL('../assets/cards/fruit-14-grapefruit.png', import.meta.url).href,
  'fruit-15': new URL('../assets/cards/fruit-15-grape.png', import.meta.url).href,
  'fruit-16': new URL('../assets/cards/fruit-16-blueberry.png', import.meta.url).href,
  'fruit-17': new URL('../assets/cards/fruit-17-blackberry.png', import.meta.url).href,
  'fruit-18': new URL('../assets/cards/fruit-18-strawberry.png', import.meta.url).href,
  'fruit-19': new URL('../assets/cards/fruit-19-cherry.png', import.meta.url).href,
  'fruit-20': new URL('../assets/cards/fruit-20-raspberry.png', import.meta.url).href,
  'fruit-21': new URL('../assets/cards/fruit-21-watermelon.png', import.meta.url).href,
  'fruit-22': new URL('../assets/cards/fruit-22-cantaloupe.png', import.meta.url).href,
  'fruit-23': new URL('../assets/cards/fruit-23-coconut.png', import.meta.url).href,
  'fruit-24': new URL('../assets/cards/fruit-24-pineapple.png', import.meta.url).href,
  'fruit-25': new URL('../assets/cards/fruit-25-kiwi.png', import.meta.url).href,
  'fruit-26': new URL('../assets/cards/fruit-26-fig.png', import.meta.url).href,
  'fruit-27': new URL('../assets/cards/fruit-27-lychee.png', import.meta.url).href,
  'fruit-28': new URL('../assets/cards/fruit-28-longan.png', import.meta.url).href,
  'fruit-29': new URL('../assets/cards/fruit-29-mango.png', import.meta.url).href,
  'fruit-30': new URL('../assets/cards/fruit-30-rambutan.png', import.meta.url).href,
  'old-maid-01': new URL('../assets/cards/old-maid-01-moldy-durian.png', import.meta.url).href,
  'old-maid-02': new URL('../assets/cards/old-maid-02-spotted-papaya.png', import.meta.url).href,
  'old-maid-03': new URL('../assets/cards/old-maid-03-spoiled-pomegranate.png', import.meta.url).href,
  'old-maid-04': new URL('../assets/cards/old-maid-04-spoiled-mangosteen.png', import.meta.url).href,
}

export const effectAccent: Record<string, string> = {
  harvest: '#d89b3c',
  shake_basket: '#8a67a8',
  sour_skip: '#b9b849',
  peek_hand: '#5b76a5',
  sweet_share: '#d95c78',
  half_exchange: '#4d99a0',
  shell_guard: '#a77849',
  careful_stocking: '#628e65',
  extra_pick: '#d97845',
  market_conveyor: '#7075a8',
  old_maid: '#865052',
}

export const effectDescription: Record<string, string> = {
  harvest: '没有额外效果，收下这篮水果。',
  shake_basket: '随机打乱你自己的全部手牌顺序；你不能决定新顺序。',
  sour_skip: '本回合交接时，跳过下一名本应行动的玩家；多个效果累加。',
  peek_hand: '查看一名其他未安全玩家的全部手牌及其左右顺序；查看后牌序不变。',
  sweet_share: '选 1 张可用手牌送给一人，再从其原有可用手牌中盲抽 1 张。',
  half_exchange: '随机找一名手牌数相同的玩家；双方各选向上取整的一半同时交换。',
  shell_guard: '保护自己 1 张手牌，直到下一次有人从你处正常暗抽。',
  careful_stocking: '将自己 1 张手牌移到任意新位置。',
  extra_pick: '立即从顺时针最近的可抽玩家处再正常暗抽 1 张。',
  market_conveyor: '所有有牌玩家同时把最左牌传给顺时针下一人。',
  old_maid: '永不配对；牌局结束时持有者落败。',
}
